name: Tests

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: "8.3"
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp
      CACHE_KEY: php-extension-cache-v1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Project Dependencies
        run: composer install -q --no-interaction

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact
